service: queens-aws-lambda

plugins:
  - serverless-offline
  - serverless-middleware

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage}
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

functions:
  # get board
  GetBoard:
    events:
      - http:
          path: /generate
          method: get
    handler: src/controllers/generateController.getBoard
    middleware:
      - src/middleware/validateBoardSize.validateBoardSize
      - src/controllers/generateController.getBoard

  # post board
  PostBoard:
    events:
      - http:
          path: /generate
          method: post
    handler: src/controllers/generateController.postBoard
    middleware:
      - src/middleware/validateBoardSize.validateBoardSize
      - src/controllers/generateController.postBoard
