service: queens-aws-lambda

plugins:
  - serverless-offline
  - serverless-middleware

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage}
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}

functions:
  # get board
  GetBoard:
    events:
      - http:
          path: /generate
          method: get
    middleware:
      pre:
        - src/middleware/validateBoardSize.validateBoardSize
    handler: src/controllers/generateController.getBoard

  # post board
  PostBoard:
    events:
      - http:
          path: /generate
          method: post
    middleware:
      pre:
        - src/middleware/validateBoardSize.validateBoardSize
    handler: src/controllers/generateController.postBoard

  PostBoard2:
    events:
      - http:
          path: /send
          method: post
    handler: src/controllers/generateController.postBoard2
